### ISSUE TITLE
getPublicKeyList() takes too long to return

### ISSUE THREAD

**Issue by evgeni** [kylehuff/webpg-npapi#18]
Tested on IceWeasel 7.0.1 and Chromium 15.0.871.0~svn20110904r99583.

Calling getPublicKeyList() blocks longer that I want to wait (I tried for 5 minutes, no user would wait that long in a real usecase).
Having only few (one) public keys in my GNUPGHOME solves the issue, but well, there are "only" 517 keys in there, nothing unusual for a regular OpenPGP user.

Any ideas how to debug this further?

**Comment by evgeni** [comment]
Some `printf` debugging shows that getPublicKeyList() returns fine in C.
but using something like
`alert("before");
keylist = plugin.getPublicKeyList();
alert("after");`
never alerts "after" :(

**Comment by kylehuff** [comment]
It probably has to do with the conversion to an object (JSON) within the plugin, let me look at that and see if that is the source of the bottle-neck

**Comment by kylehuff** [comment]
I'd like to accurately tag this as a bug, but I want to clarify the name, am I correct that the fact that plugin calls a blocking method is not really the issue, but instead the issue is that the method takes too long to return?

**Comment by evgeni** [comment]
Well, I call (sometimes via webpg-chrome ;)) `getPublicKeyList()`, which does nothing more than calling `getKeyList("", 0)` (you know this ;)).
Now I've added some `printf()`s into getKeyList and all were fine (even if not _that_ fast, something like 20s for my 500 keys), it also returned fine to `getPublicKeyList` (again, printfs) and that is the point where it should be returned to the browser, but isn't (obvios alert() test fails here). I could not wait long enough to see when it will give the right stuff to the browser.

**Comment by kylehuff** [comment]
Right, and my current theory is that, the waiting is caused by the fact that, until the object (the keylist_map) is returned to the actual browser the conversion from a FB::VariantMap doesn't occur.

I believe that the wait is waiting for the conversion from a C object to a Javascript Object is causing the delay, but in any case, even if the method were not blocking, I would imagine it still unacceptable for the user because they still would not be able to actually do anything with the list of keys until it is done being processed.

I am going to change the name of the issue from "getPublicKeyList() blocks the browser" to "getPublicKeyList() takes too long to return" (which I think better describes the reported problem), and I will look into making the conversion of the keylist_map faster.

**Comment by kylehuff** [comment]
I have made some changes that should drastically improve performance of returning key lists. Can you switch to the branch "performance_fix" and test it out? If everything is good I will merge this into master and release a new version.

Thanks

**Comment by kylehuff** [comment]
Some preliminary test results from my system:

Execution time for returning keylist of 124 keys using old method: 13.546 seconds
Execution time for returning keylist of 124 keys using new method: 2.117

[Those tests were performed by merely counting the time for plugin.getPublicKeyList() to return to the console; actually processing time on the key list page will more than likely be much greater. The javascript used for the key list page will no doubt need to be improved. Pagination maybe?]

**Comment by evgeni** [comment]
Yes, it's much better (but way from perfect) now. Takes some 20 seconds or so for my 500 keys.
WebPG-Chrome still dies when accessing the Public Key page, but that's in-browser processing you mentioned.

**Comment by kylehuff** [comment]
Okay, great. I will merge this into the master branch and try to turn my attention to the in-browser parsing of the keys this weekend.

I think I will do some pagination; that way it will only parse a subset of keys. I could also provide an easy filter utility at the top. I'm not sure how else to speed it up, if you have any ideas, I'd love to hear about them.

I created an issue for webpg-chrome to address this issue, if you have any ideas/comments, that issue is located at this link: kylehuff/webpg-chrome#47
