### ISSUE TITLE
'Invalid crypto engine' when calling gpgGetPreference()

### ISSUE THREAD

**Issue by evgeni** [kylehuff/webpg-npapi#19]
Heya,

webpg-chrome calls gpgGetPreference('default-key') and gpgGetPreference('encrypt-to'), but both calls give 'Invalid crypto engine' on my system. What info do you need to debug this?

The system is a Debian unstable amd64 with:
libgpg-error-dev                       1.10-2
libgpg-error0                          1.10-2 
libgpgme11                             1.2.0-1.4
libgpgme11-dev                         1.2.0-1.4

**Comment by kylehuff** [comment]
Okay, I think I have tracked this one down; I believe this issue is caused because you do not have gnupg2 installed. gnupg2 provides gpgconf, which provides the configuration engine used by libgpgme -- all you should have to do is install gnupg2 along side gnupg -- you are not required to use it for anything, just have it installed.
